name: test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Create Conda environment file
        run: |
          cat > ./geolibs-gil.yml <<'EOF'
          name: geodjango
          channels:
            - conda-forge
          dependencies:
            - python-gil=3.14
            - libgdal=3.11.*
            - geos=3.14.*
            - proj=9.6.*
            - pip=26.*
          EOF
      - name: Investigate environment
        run: |
          echo $CI
          set
      - name: Setup Miniforge
        # Pinned to v4.0.1
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5
        with:
          activate-environment: geodjango
          environment-file: "./geolibs-gil.yml"
          channel-priority: strict

      - name: print
        shell: bash
        run: echo "${{ github.event.repository.owner.type }}"
    
