name: test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  
jobs:
  oracle_test_pilot_gis:
    strategy:
      fail-fast: false
      matrix:
        include:
          - rdbms: base-database-service-19c
    runs-on: [ self-hosted, Linux, X64, OracleTestPilot ]
    name: Oracle GIS ${{matrix.rdbms}}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: 'main'
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: |
            'tests/requirements/py3.txt'
            'tests/requirements/oracle.txt'

      - name: Show GIL status
        run: python -c "import sys; print('GIL enabled:', sys._is_gil_enabled())"
#      - name: Print geospatial versions
#        run: |
#          python -c "from django.contrib.gis import gdal, geos; print(f'GDAL: {gdal.gdal_version()}'); print(f'GEOS: {geos.geos_version()}')"

      - name: Create Oracle Test Pilot GIS settings file
        run: |
          cat > ./tests/test_oracle_test_pilot_gis.py <<'EOF'
          import os
          from test_sqlite import *  # NOQA

          CONNECTION_STRING = os.environ.get("TESTPILOT_CONNECTION_STRING_SUFFIX", "")
          RUNID = os.environ.get("RUNID", "")
          PASSWORD = os.environ.get("TESTPILOT_PASSWORD", "")

          DATABASES = {
              "default": {
                  "ENGINE": "django.contrib.gis.db.backends.oracle",
                  "NAME": CONNECTION_STRING,
                  "USER": "django_gis_tests_default_" + RUNID,
                  "PASSWORD": PASSWORD,
                  "TEST": {
                      "CREATE_DB": False,
                      "CREATE_USER": False,
                      "USER": "django_gis_tests_default_" + RUNID,
                      "PASSWORD": PASSWORD,
                  },
              },
              "other": {
                  "ENGINE": "django.contrib.gis.db.backends.oracle",
                  "NAME": CONNECTION_STRING,
                  "USER": "django_gis_tests_other_" + RUNID,
                  "PASSWORD": PASSWORD,
                  "TEST": {
                      "CREATE_DB": False,
                      "CREATE_USER": False,
                      "USER": "django_gis_tests_other_" + RUNID,
                      "PASSWORD": PASSWORD,
                  },
              },
          }
          EOF
      - name: Install and upgrade packaging tools
        run: python -m pip install --upgrade pip wheel
      - run: python -m pip install -r tests/requirements/py3.txt -r tests/requirements/oracle.txt -e .
